export const IPC_CHANNELS = {
  aiProviders: {
    create: 'ai-providers:create',
    delete: 'ai-providers:delete',
    list: 'ai-providers:list',
    listRoutes: 'ai-providers:list-routes',
    testConnection: 'ai-providers:test-connection',
    update: 'ai-providers:update',
    upsertRoute: 'ai-providers:upsert-route',
  },
  app: {
    getRuntimeInfo: 'app:get-runtime-info',
  },
  problems: {
    addImages: 'problems:add-images',
    create: 'problems:create',
    delete: 'problems:delete',
    list: 'problems:list',
    readImage: 'problems:read-image',
    removeImage: 'problems:remove-image',
    removeRelation: 'problems:remove-relation',
    update: 'problems:update',
    upsertRelation: 'problems:upsert-relation',
  },
  problemAnalysis: {
    analyze: 'problem-analysis:analyze',
    chooseImages: 'problem-analysis:choose-images',
    commit: 'problem-analysis:commit',
  },
  templates: {
    create: 'templates:create',
    performAction: 'templates:perform-action',
    readSource: 'templates:read-source',
  },
  templateManagement: {
    applyFilePlan: 'template-management:apply-file-plan',
    auditWorkspace: 'template-management:audit-workspace',
    cancelFilePlan: 'template-management:cancel-file-plan',
    chooseImportSource: 'template-management:choose-import-source',
    classify: 'template-management:classify',
    deleteTemplate: 'template-management:delete-template',
    getMetadata: 'template-management:get-metadata',
    importTemplate: 'template-management:import-template',
    generateFilePlan: 'template-management:generate-file-plan',
    listFileExecutions: 'template-management:list-file-executions',
    listFilePlans: 'template-management:list-file-plans',
    redraftFilePlan: 'template-management:redraft-file-plan',
    rollbackFileExecution: 'template-management:rollback-file-execution',
    updateMetadata: 'template-management:update-metadata',
  },
  workspace: {
    choose: 'workspace:choose',
    getCurrent: 'workspace:get-current',
    rescan: 'workspace:rescan',
  },
} as const
