export const IPC_CHANNELS = {
  aiProviders: {
    create: 'ai-providers:create',
    delete: 'ai-providers:delete',
    list: 'ai-providers:list',
    listRoutes: 'ai-providers:list-routes',
    testConnection: 'ai-providers:test-connection',
    update: 'ai-providers:update',
    upsertRoute: 'ai-providers:upsert-route',
  },
  app: {
    getRuntimeInfo: 'app:get-runtime-info',
  },
  dataManagement: {
    diagnose: 'data-management:diagnose',
    exportBackup: 'data-management:export-backup',
    inspectBackupLifecycle: 'data-management:inspect-backup-lifecycle',
    previewCleanup: 'data-management:preview-cleanup',
    previewInterruptedRecovery: 'data-management:preview-interrupted-recovery',
    previewQuarantineRelease: 'data-management:preview-quarantine-release',
    previewRestore: 'data-management:preview-restore',
    quarantineCleanup: 'data-management:quarantine-cleanup',
    recoverInterruptedOperation: 'data-management:recover-interrupted-operation',
    releaseQuarantine: 'data-management:release-quarantine',
    restoreBackup: 'data-management:restore-backup',
    undoCleanup: 'data-management:undo-cleanup',
    verifyBackup: 'data-management:verify-backup',
  },
  problems: {
    addImages: 'problems:add-images',
    create: 'problems:create',
    delete: 'problems:delete',
    list: 'problems:list',
    readImage: 'problems:read-image',
    removeImage: 'problems:remove-image',
    removeRelation: 'problems:remove-relation',
    update: 'problems:update',
    upsertRelation: 'problems:upsert-relation',
  },
  problemAnalysis: {
    analyze: 'problem-analysis:analyze',
    cancel: 'problem-analysis:cancel',
    chooseImages: 'problem-analysis:choose-images',
    commit: 'problem-analysis:commit',
    preview: 'problem-analysis:preview',
  },
  templates: {
    create: 'templates:create',
    performAction: 'templates:perform-action',
    readSource: 'templates:read-source',
  },
  templateManagement: {
    applyTemplateRelocation: 'template-management:apply-template-relocation',
    applyFilePlan: 'template-management:apply-file-plan',
    archiveFilePlans: 'template-management:archive-file-plans',
    auditWorkspace: 'template-management:audit-workspace',
    cancelFilePlanGeneration: 'template-management:cancel-file-plan-generation',
    cancelClassification: 'template-management:cancel-classification',
    cancelFilePlan: 'template-management:cancel-file-plan',
    chooseBatchImportDirectory: 'template-management:choose-batch-import-directory',
    chooseBatchImportFiles: 'template-management:choose-batch-import-files',
    chooseImportSource: 'template-management:choose-import-source',
    classify: 'template-management:classify',
    deleteTemplate: 'template-management:delete-template',
    exportFilePlanDiagnostic: 'template-management:export-file-plan-diagnostic',
    getMetadata: 'template-management:get-metadata',
    importTemplate: 'template-management:import-template',
    importTemplatesBatch: 'template-management:import-templates-batch',
    inspectBatchImport: 'template-management:inspect-batch-import',
    previewBatchClassification: 'template-management:preview-batch-classification',
    previewClassification: 'template-management:preview-classification',
    previewFilePlan: 'template-management:preview-file-plan',
    previewTemplateRelocation: 'template-management:preview-template-relocation',
    generateFilePlan: 'template-management:generate-file-plan',
    listFileExecutions: 'template-management:list-file-executions',
    listFilePlans: 'template-management:list-file-plans',
    redraftFilePlan: 'template-management:redraft-file-plan',
    rollbackFileExecution: 'template-management:rollback-file-execution',
    updateMetadata: 'template-management:update-metadata',
  },
  workspace: {
    choose: 'workspace:choose',
    getCurrent: 'workspace:get-current',
    rescan: 'workspace:rescan',
  },
} as const
