export const IPC_CHANNELS = {
  backgroundTasks: {
    cancel: 'background-tasks:cancel',
    get: 'background-tasks:get',
  },
  aiProviders: {
    create: 'ai-providers:create',
    delete: 'ai-providers:delete',
    list: 'ai-providers:list',
    listRoutes: 'ai-providers:list-routes',
    testConnection: 'ai-providers:test-connection',
    update: 'ai-providers:update',
    upsertRoute: 'ai-providers:upsert-route',
  },
  app: {
    getRuntimeInfo: 'app:get-runtime-info',
  },
  dataManagement: {
    diagnose: 'data-management:diagnose',
    exportBackup: 'data-management:export-backup',
    inspectBackupLifecycle: 'data-management:inspect-backup-lifecycle',
    previewInterruptedRecovery: 'data-management:preview-interrupted-recovery',
    previewRestore: 'data-management:preview-restore',
    recoverInterruptedOperation: 'data-management:recover-interrupted-operation',
    restoreBackup: 'data-management:restore-backup',
    verifyBackup: 'data-management:verify-backup',
  },
  problems: {
    addImages: 'problems:add-images',
    create: 'problems:create',
    delete: 'problems:delete',
    get: 'problems:get',
    list: 'problems:list',
    listByTemplate: 'problems:list-by-template',
    listPage: 'problems:list-page',
    readImage: 'problems:read-image',
    removeImage: 'problems:remove-image',
    removeRelation: 'problems:remove-relation',
    update: 'problems:update',
    upsertRelation: 'problems:upsert-relation',
  },
  problemAnalysis: {
    analyze: 'problem-analysis:analyze',
    cancel: 'problem-analysis:cancel',
    chooseImages: 'problem-analysis:choose-images',
    commit: 'problem-analysis:commit',
    preview: 'problem-analysis:preview',
  },
  templates: {
    applySourceEdit: 'templates:apply-source-edit',
    create: 'templates:create',
    getSummary: 'templates:get-summary',
    listPage: 'templates:list-page',
    performAction: 'templates:perform-action',
    previewSourceEdit: 'templates:preview-source-edit',
    readSource: 'templates:read-source',
  },
  templateManagement: {
    applyExistingMetadataCompletion: 'template-management:apply-existing-metadata-completion',
    applyTemplateRelocation: 'template-management:apply-template-relocation',
    applyFilePlan: 'template-management:apply-file-plan',
    auditWorkspace: 'template-management:audit-workspace',
    startAudit: 'template-management:start-audit',
    cancelFilePlanGeneration: 'template-management:cancel-file-plan-generation',
    cancelClassification: 'template-management:cancel-classification',
    cancelFilePlan: 'template-management:cancel-file-plan',
    chooseBatchImportDirectory: 'template-management:choose-batch-import-directory',
    chooseBatchImportFiles: 'template-management:choose-batch-import-files',
    chooseImportSource: 'template-management:choose-import-source',
    classify: 'template-management:classify',
    deleteTemplate: 'template-management:delete-template',
    deleteFileExecutions: 'template-management:delete-file-executions',
    deleteInvalidFileExecutions: 'template-management:delete-invalid-file-executions',
    deleteFilePlans: 'template-management:delete-file-plans',
    exportFilePlanDiagnostic: 'template-management:export-file-plan-diagnostic',
    getMetadata: 'template-management:get-metadata',
    importTemplate: 'template-management:import-template',
    importTemplatesBatch: 'template-management:import-templates-batch',
    inspectBatchImport: 'template-management:inspect-batch-import',
    previewBatchClassification: 'template-management:preview-batch-classification',
    previewClassification: 'template-management:preview-classification',
    previewExistingMetadataCompletion: 'template-management:preview-existing-metadata-completion',
    previewFilePlan: 'template-management:preview-file-plan',
    previewDeleteFileExecutions: 'template-management:preview-delete-file-executions',
    previewDeleteInvalidFileExecutions:
      'template-management:preview-delete-invalid-file-executions',
    previewDeleteFilePlans: 'template-management:preview-delete-file-plans',
    previewTemplateRelocation: 'template-management:preview-template-relocation',
    generateFilePlan: 'template-management:generate-file-plan',
    generateExistingMetadataCompletion: 'template-management:generate-existing-metadata-completion',
    listFileExecutions: 'template-management:list-file-executions',
    listFileExecutionsPage: 'template-management:list-file-executions-page',
    listInvalidFileExecutionsPage: 'template-management:list-invalid-file-executions-page',
    listFilePlans: 'template-management:list-file-plans',
    listFilePlansPage: 'template-management:list-file-plans-page',
    redraftFilePlan: 'template-management:redraft-file-plan',
    rollbackFileExecution: 'template-management:rollback-file-execution',
    updateMetadata: 'template-management:update-metadata',
  },
  workspace: {
    choose: 'workspace:choose',
    getCurrent: 'workspace:get-current',
    rescan: 'workspace:rescan',
    startRescan: 'workspace:start-rescan',
  },
} as const
